/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("io.github.shanepark.tableparser.kotlin-common-conventions")
    id("org.springframework.boot") version "3.0.4"
    id("io.spring.dependency-management") version "1.0.14.RELEASE"
    kotlin("plugin.spring") version "1.7.21"
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation(project(":table-parser-core"))
}
