POST localhost:8080/excel

<table>
  <thead>
  <tr>
    <th colspan="2">Java</th>
    <th colspan="2">Python</th>
    <th colspan="2">Ruby</th>
  </tr>
  <tr>
    <th>Men</th>
    <th>Women</th>
    <th>Men</th>
    <th>Women</th>
    <th>Men</th>
    <th>Women</th>
  </tr>
  </thead>
  <tbody>
  <tr>
    <td>82</td>
    <td>85</td>
    <td>78</td>
    <td>82</td>
    <td>77</td>
    <td>81</td>
  </tr>
  </tbody>
</table>
